"""Initial migration

Revision ID: 3b60c3b51c6d
Revises: 
Create Date: 2024-05-19 22:36:34.349621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b60c3b51c6d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Games',
    sa.Column('UID', sa.Text(), nullable=False),
    sa.Column('Name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('UID'),
    sa.UniqueConstraint('UID')
    )
    op.create_table('Tags',
    sa.Column('TagID', sa.Text(), nullable=False),
    sa.Column('Name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('TagID'),
    sa.UniqueConstraint('TagID')
    )
    op.create_table('Users',
    sa.Column('UID', sa.Text(), nullable=False),
    sa.Column('Username', sa.Text(), nullable=False),
    sa.Column('Password', sa.Text(), nullable=False),
    sa.Column('Email', sa.Text(), nullable=False),
    sa.Column('IsAdmin', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('UID'),
    sa.UniqueConstraint('Email'),
    sa.UniqueConstraint('UID')
    )
    op.create_table('Lobby',
    sa.Column('LobbyID', sa.Text(), nullable=False),
    sa.Column('GameID', sa.Text(), nullable=False),
    sa.Column('Desc', sa.Text(), nullable=True),
    sa.Column('Name', sa.Text(), nullable=True),
    sa.Column('maxPlayers', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['GameID'], ['Games.UID'], name='fk_lobby_game'),
    sa.PrimaryKeyConstraint('LobbyID'),
    sa.UniqueConstraint('LobbyID')
    )
    op.create_table('LobbyPlayers',
    sa.Column('RowID', sa.Text(), nullable=False),
    sa.Column('LobbyID', sa.Text(), nullable=False),
    sa.Column('UserID', sa.Text(), nullable=False),
    sa.Column('IsHost', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['LobbyID'], ['Lobby.LobbyID'], name='fk_lobby_players_lobby'),
    sa.ForeignKeyConstraint(['UserID'], ['Users.UID'], name='fk_lobby_players_user'),
    sa.PrimaryKeyConstraint('RowID'),
    sa.UniqueConstraint('RowID')
    )
    op.create_table('LobbyTags',
    sa.Column('RowID', sa.Text(), nullable=False),
    sa.Column('LobbyID', sa.Text(), nullable=False),
    sa.Column('TagID', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['LobbyID'], ['Lobby.LobbyID'], name='fk_lobby_tags_lobby'),
    sa.ForeignKeyConstraint(['TagID'], ['Tags.TagID'], name='fk_lobby_tags_tag'),
    sa.PrimaryKeyConstraint('RowID'),
    sa.UniqueConstraint('RowID')
    )
    op.create_table('LobbyTimes',
    sa.Column('RowID', sa.Text(), nullable=False),
    sa.Column('LobbyID', sa.Text(), nullable=False),
    sa.Column('TimeBlockStart', sa.Text(), nullable=False),
    sa.Column('DayOfWeek', sa.Text(), nullable=False),
    sa.Column('TimeBlockEnd', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['LobbyID'], ['Lobby.LobbyID'], name='fk_lobby_times_lobby'),
    sa.PrimaryKeyConstraint('RowID'),
    sa.UniqueConstraint('RowID')
    )
    op.create_table('UserTracker',
    sa.Column('RowID', sa.Text(), nullable=False),
    sa.Column('LobbyID', sa.Text(), nullable=False),
    sa.Column('UserID', sa.Text(), nullable=False),
    sa.Column('Action', sa.Text(), nullable=False),
    sa.Column('Desc', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['LobbyID'], ['Lobby.LobbyID'], name='fk_user_tracker_lobby'),
    sa.ForeignKeyConstraint(['UserID'], ['Users.UID'], name='fk_user_tracker_user'),
    sa.PrimaryKeyConstraint('RowID'),
    sa.UniqueConstraint('RowID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UserTracker')
    op.drop_table('LobbyTimes')
    op.drop_table('LobbyTags')
    op.drop_table('LobbyPlayers')
    op.drop_table('Lobby')
    op.drop_table('Users')
    op.drop_table('Tags')
    op.drop_table('Games')
    # ### end Alembic commands ###
