"""add flaskgroup

Revision ID: b08e8395dd5b
Revises: 76f5e9420133
Create Date: 2024-05-10 14:32:18.413224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b08e8395dd5b'
down_revision = '76f5e9420133'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Lobby', schema=None) as batch_op:
        batch_op.add_column(sa.Column('LobbyID', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('GameID', sa.Text(), nullable=False))
        batch_op.create_unique_constraint("unique_lobby_id", ['LobbyID'])
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key("fk_game_id", 'Games', ['GameID'], ['UID'])
        batch_op.drop_column('LobbyId')
        batch_op.drop_column('GameId')

    with op.batch_alter_table('LobbyPlayers', schema=None) as batch_op:
        batch_op.alter_column('RowID',
               existing_type=sa.NullType(),
               nullable=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key("fk_lobby_players_lobby_id", 'Lobby', ['LobbyID'], ['LobbyID'])

    with op.batch_alter_table('LobbyTags', schema=None) as batch_op:
        batch_op.alter_column('RowID',
               existing_type=sa.NullType(),
               nullable=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key("fk_lobby_tags_lobby_id", 'Lobby', ['LobbyID'], ['LobbyID'])

    with op.batch_alter_table('LobbyTimes', schema=None) as batch_op:
        batch_op.create_unique_constraint("unique_repeat", ['Repeat'])
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key("fk_lobby_times_lobby_id", 'Lobby', ['LobbyID'], ['LobbyID'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('LobbyTimes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key("fk_lobby_times_lobby_id", 'Lobby', ['LobbyID'], ['LobbyId'])
        batch_op.drop_constraint("unique_repeat", type_='unique')

    with op.batch_alter_table('LobbyTags', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key("fk_lobby_tags_lobby_id", 'Lobby', ['LobbyID'], ['LobbyId'])
        batch_op.alter_column('RowID',
               existing_type=sa.NullType(),
               nullable=True)

    with op.batch_alter_table('LobbyPlayers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key("fk_lobby_players_lobby_id", 'Lobby', ['LobbyID'], ['LobbyId'])
        batch_op.alter_column('RowID',
               existing_type=sa.NullType(),
               nullable=True)

    with op.batch_alter_table('Lobby', schema=None) as batch_op:
        batch_op.add_column(sa.Column('GameId', sa.TEXT(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('LobbyId', sa.TEXT(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key("fk_game_id", 'Games', ['GameId'], ['UID'])
        batch_op.drop_constraint("unique_lobby_id", type_='unique')
        batch_op.drop_column('GameID')
        batch_op.drop_column('LobbyID')

    # ### end Alembic commands ###
