"""Remove LobbyID, RowID->Time

Revision ID: e707b4483405
Revises: 3b60c3b51c6d
Create Date: 2024-05-20 02:04:01.294894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e707b4483405'
down_revision = '3b60c3b51c6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('UserTracker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Time', sa.Text(), nullable=False))
        batch_op.create_unique_constraint(None, ['Time'])
        batch_op.drop_constraint('fk_user_tracker_lobby', type_='foreignkey')
        batch_op.drop_column('RowID')
        batch_op.drop_column('LobbyID')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('UserTracker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('LobbyID', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('RowID', sa.TEXT(), nullable=False))
        batch_op.create_foreign_key('fk_user_tracker_lobby', 'Lobby', ['LobbyID'], ['LobbyID'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('Time')

    # ### end Alembic commands ###
